version: "3.7"

services:
  api:
    ports:
      - "5000:5000"
    build:
      context: ./api
    volumes:
      - ./api/src:/home/user/src
    restart: always

  frontend:
    ports:
      - "80:80"
    environment:
      - PORT=80
    build:
      context: ./interface/web
      target: dev
    volumes:
      - ./interface/web/src:/app/src
      - ./interface/web/public:/app/public
    restart: always